package:
  name: replicards
  version: "1.0.0"

source:
  path: ../

build:
  noarch: python
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
    - numpy
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib

about:
  home: "https://github.com/eliamascolo/replicards"
  license: "MIT"
  summary: "An interactive way of teaching biological evolution through a card game. The aim of this interactive class is to demonstrate how replicants that can inherit mutations can undergo evolution by natural selection if the inheritable characteristics can affect their reproductive success."
  description: "An interactive way of teaching biological evolution through a card game."
