package:
  name: replicards
  version: "1.0.0"

source:
  path: ../

build:
  noarch: python
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
    - numpy
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib

about:
  home: "https://github.com/eliamascolo/replicards"
  license: "MIT"
  summary: "An interactive way of teaching biological evolution through a card game."
  description: "An interactive way of teaching biological evolution through a card game."
