project:
  type: website

website:
  title: "Replicards"
  favicon: logo-icon.png
  site-path: replicards.qmd
  google-analytics: "G-3HLZHZMB0V"
  back-to-top-navigation: true
  page-footer: "*Original idea: Elia Mascolo & Yseult Héjja-Brichard*" 
  navbar:
    logo: logo.svg
    left:
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



