project:
  type: website

website:
  title: "Replicards"
  favicon: logo-icon.png
  image: "/images/replicards_social_media_preview.jpg"
  site-url: https://replicards.netlify.app/
  open-graph: true
  twitter-card: true
  google-analytics: "G-3HLZHZMB0V"
  back-to-top-navigation: true
  navbar:
    logo: logo.svg
    left:
      - href: index.qmd
      - text: Contact Us
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/eliamascolo/replicards
  page-footer:
    border: true
    center: "*Original idea: Elia Mascolo & Yseult Héjja-Brichard*" 
    right: "made with 🍕 🍹 & [Quarto](https://quarto.org)"
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto
