project:
  type: website

website:
  title: "Replicards"
  favicon: logo-icon.png
  google-analytics: "G-3HLZHZMB0V"
  back-to-top-navigation: true
  navbar:
    logo: logo.svg
    left:
      - href: index.qmd
  page-footer:
    border: true
    center: "*Original idea: Elia Mascolo & Yseult Héjja-Brichard*" 
    right: "made with ︎♥️ & [Quarto](https://quarto.org)"
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto
