project:
  type: website
  output-dir: docs

website:
  title: "Replicards"
  navbar:
    left:
      - replicards.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true